version: '3.8'
services:
  scraper:
    restart: always
    build: ./scraper
    ports:
      - 2000:2000
    environment:
      - PORT=2000

  listing:
    restart: always
    build: ./listing
    ports:
      - 5000:5000
    environment:
      - PORT=5000
      - SCRAPER_HOST=http://scraper:2000
      - MY_PASSWORD=s0uLfly.1998
      - MY_DATABASE=PricesAroundTheGlobe
    depends_on:
      - scraper
